# Generated by Django 5.2.7 on 2025-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='sushiswap_asm_fiat_to_token',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='sushiswap_asm_token_to_fiat',
            field=models.FloatField(default=3),
        ),
    ]
