# Generated by Django 5.2.7 on 2025-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='INDICATORS',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='MINUTES',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='live_indicators',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='tokens',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='vision',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
