# Generated by Django 5.2.5 on 2025-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='balancesa',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='balances',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
