# Generated by Django 5.2.7 on 2025-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='command_arguments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='command_function',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
