# Generated by Django 5.2.5 on 2025-08-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_adminsettings_balancesa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='risk_factor',
        ),
        migrations.AddField(
            model_name='position',
            name='ambition_ratio',
            field=models.FloatField(default=0),
        ),
    ]
