# Generated by Django 5.2.7 on 2025-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adminsettings_sushiswap_asm_fiat_to_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address_to_transfer_to',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('uniswap_approve', 'uniswap_approve'), ('uniswap_token_to_fiat', 'uniswap_token_to_fiat'), ('uniswap_fiat_to_token', 'uniswap_fiat_to_token'), ('uniswap_wrap_eth', 'uniswap_wrap_eth'), ('uniswap_unwrap_weth', 'uniswap_unwrap_weth'), ('uniswap_transfer_token', 'uniswap_transfer_token'), ('sushiswap_token_to_fiat', 'sushiswap_token_to_fiat'), ('sushiswap_fiat_to_token', 'sushiswap_fiat_to_token'), ('aave_approve', 'aave_approve'), ('aave_supply', 'aave_supply'), ('aave_withdraw', 'aave_withdraw'), ('aave_borrow', 'aave_borrow'), ('aave_repay', 'aave_repay'), ('arbi_balance', 'arbi_balance'), ('arbi_action_2', 'arbi_action_2'), ('arbi_approve', 'arbi_approve'), ('arbi_allowance', 'arbi_allowance'), ('arbi_deposit', 'arbi_deposit'), ('arbi_withdraw', 'arbi_withdraw'), ('arbi_wrap_eth', 'arbi_wrap_eth'), ('arbi_unwrap_weth', 'arbi_unwrap_weth'), ('arbi_single_swap', 'arbi_single_swap')], default='uniswap_token_to_fiat'),
        ),
    ]
