# Generated by Django 5.2.7 on 2025-10-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_adminsettings_command_arguments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='live_indicators',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='live_indicators_update_epoch',
            field=models.BigIntegerField(default=0),
        ),
    ]
