# Generated by Django 5.2.7 on 2025-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_adminsettings_indicators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='liquidity',
        ),
        migrations.RemoveField(
            model_name='token',
            name='ll_ratio',
        ),
        migrations.RemoveField(
            model_name='token',
            name='ll_worth_by_weth',
        ),
        migrations.RemoveField(
            model_name='token',
            name='security_issues',
        ),
        migrations.AddField(
            model_name='token',
            name='go_plus_dex_liquidity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='go_plus_locked_lp_ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='go_plus_lp_total_supply',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='go_plus_security_issues',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
