# Generated by Django 5.2.5 on 2025-08-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_position_risk_factor_position_ambition_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='display_on_chart',
            field=models.BooleanField(default=True),
        ),
    ]
