# Generated by Django 5.2.7 on 2025-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_adminsettings_live_indicators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='indicators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='minutes',
            field=models.JSONField(default=list),
        ),
    ]
