# Generated by Django 5.2.7 on 2025-10-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_token_liquidity_remove_token_ll_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='investigation_red_flag',
            field=models.BooleanField(default=False),
        ),
    ]
