# Generated by Django 5.2.7 on 2025-11-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_token_investigation_red_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='auto_purchase_fiat_amount',
            field=models.FloatField(default=1),
        ),
    ]
