# Generated by Django 5.2.5 on 2025-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_position_display_on_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uniswap_version',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
