# Generated by Django 5.2.7 on 2025-10-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_adminsettings_indicators_adminsettings_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='minutes',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='INDICATORS',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='MINUTES',
            field=models.JSONField(default=list),
        ),
    ]
