# Generated by Django 5.2.7 on 2025-10-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_adminsettings_indicators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='active_time_frame_length',
            field=models.IntegerField(default=1440),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='active_time_frame_minutes',
            field=models.IntegerField(default=1),
        ),
    ]
