# Generated by Django 5.2.5 on 2025-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_transaction_uniswap_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='max_allowed_alipage',
            field=models.FloatField(default=0.01),
        ),
    ]
