# Generated by Django 5.2.7 on 2025-11-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_pair_reserves',
        ),
    ]
