# Generated by Django 5.2.5 on 2025-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_adminsettings_max_allowed_alipage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='max_allowed_alipage',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='max_allowed_slipage',
            field=models.FloatField(default=0.01),
        ),
    ]
