# Generated by Django 5.2.7 on 2025-10-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_adminsettings_active_time_frame_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='live_indicators_update_epoch',
        ),
    ]
