# Generated by Django 5.2.7 on 2025-10-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_adminsettings_live_indicators_update_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='vision',
            field=models.JSONField(default=dict),
        ),
    ]
