# Generated by Django 5.2.5 on 2025-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_adminsettings_max_allowed_alipage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='eth_amount_recieved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='eth_amount_spent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='eth_effective_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='eth_nominal_price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('TRX', 'TRX'), ('SOL', 'SOL')], default='ETH'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_amount_recieved',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_amount_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_effective_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_nominal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('token_to_dai', 'token_to_dai'), ('dai_to_token', 'dai_to_token')], default='token_to_dai'),
        ),
    ]
