# Generated by Django 5.2.7 on 2025-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_adminsettings_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chain_id', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True, unique=True)),
                ('url', models.TextField(blank=True, default='', null=True)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('pair', models.TextField(blank=True, default='', null=True)),
                ('price', models.FloatField(default=0)),
                ('age', models.BigIntegerField(default=0)),
                ('txns', models.BigIntegerField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('makers', models.BigIntegerField(default=0)),
                ('m5', models.FloatField(default=0)),
                ('h1', models.FloatField(default=0)),
                ('h6', models.FloatField(default=0)),
                ('h24', models.FloatField(default=0)),
                ('liquidity', models.FloatField(default=0)),
                ('cap', models.FloatField(default=0)),
            ],
        ),
    ]
