# Generated by Django 5.2.5 on 2025-08-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_transaction_eth_amount_recieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='coin',
            field=models.CharField(choices=[('wbtc', 'wbtc'), ('eth', 'eth'), ('trx', 'trx'), ('sol', 'sol')], default='wbtc'),
        ),
        migrations.AlterField(
            model_name='position',
            name='coin',
            field=models.CharField(choices=[('wbtc', 'wbtc'), ('eth', 'eth'), ('trx', 'trx'), ('sol', 'sol')], default='eth'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(choices=[('wbtc', 'wbtc'), ('eth', 'eth'), ('trx', 'trx'), ('sol', 'sol')], default='eth'),
        ),
    ]
