# Generated by Django 5.2.7 on 2025-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='orders_paid_for_of_token',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='token',
            name='pairs',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='token',
            name='pairs_with_the_pair',
            field=models.JSONField(default=dict),
        ),
    ]
