# Generated by Django 5.2.5 on 2025-08-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_candle_coin_alter_position_coin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='gas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='prices',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
