# Generated by Django 5.2.5 on 2025-08-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_adminsettings_gas_adminsettings_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='gas_update_epoch',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='prices_update_epoch',
            field=models.BigIntegerField(default=0),
        ),
    ]
