# Generated by Django 5.2.7 on 2025-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_token_orders_paid_for_of_token_token_pairs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pools',
            field=models.JSONField(default=dict),
        ),
    ]
