# Generated by Django 5.2.5 on 2025-08-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_adminsettings_gas_update_epoch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='coin',
            field=models.CharField(choices=[('eth', 'eth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='wbtc'),
        ),
        migrations.AlterField(
            model_name='position',
            name='coin',
            field=models.CharField(choices=[('eth', 'eth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='eth'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(choices=[('eth', 'eth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='eth'),
        ),
    ]
