# Generated by Django 5.2.5 on 2025-08-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_candle_coin_alter_position_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='max_allowed_slipage',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='secure_profit_ratio',
            field=models.FloatField(default=0.7),
        ),
    ]
