# Generated by Django 5.2.7 on 2025-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_token_age_alter_token_cap_alter_token_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='tokens',
            field=models.JSONField(default=dict),
        ),
    ]
