# Generated by Django 5.2.5 on 2025-09-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_adminsettings_max_allowed_slipage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='fiat_coin',
            field=models.CharField(choices=[('dai', 'dai'), ('usdc', 'usdc'), ('usdt', 'usdt')], default='usdt'),
        ),
    ]
