# Generated by Django 5.2.7 on 2025-10-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_adminsettings_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
