# Generated by Django 5.2.5 on 2025-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_adminsettings_fiat_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='coin',
            field=models.CharField(choices=[('weth', 'weth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='wbtc'),
        ),
        migrations.AlterField(
            model_name='position',
            name='coin',
            field=models.CharField(choices=[('weth', 'weth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='weth'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(choices=[('weth', 'weth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='weth'),
        ),
    ]
