# Generated by Django 5.2.7 on 2025-10-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_token_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
