# Generated by Django 5.2.5 on 2025-09-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_candle_coin_alter_position_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='dai_amount_recieved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='dai_amount_spent',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_amount_recieved',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_amount_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('token_to_fiat', 'token_to_fiat'), ('fiat_to_token', 'fiat_to_token')], default='token_to_fiat'),
        ),
    ]
