# Generated by Django 5.2.7 on 2025-10-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_token_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='txns',
        ),
        migrations.AddField(
            model_name='token',
            name='uniswap_version',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='tokens',
            field=models.JSONField(default=list),
        ),
    ]
