# Generated by Django 5.2.7 on 2025-10-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_token_txns_token_uniswap_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uniswap_version',
            field=models.CharField(blank=True, choices=[('v2', 'v2'), ('v3', 'v3'), ('v4', 'v4')], null=True),
        ),
    ]
