# Generated by Django 5.2.5 on 2025-09-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_transaction_dai_amount_recieved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='added_slipage_ratio',
            field=models.FloatField(default=0.5),
        ),
    ]
