# Generated by Django 5.2.7 on 2025-10-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_token_uniswap_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='uniswap_version',
        ),
        migrations.AddField(
            model_name='token',
            name='version',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
