# Generated by Django 5.2.5 on 2025-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_adminsettings_added_slipage_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='added_slipage_ratio',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='added_slipage_multiplier',
            field=models.FloatField(default=3),
        ),
    ]
