# Generated by Django 5.2.7 on 2025-10-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_token_uniswap_version_token_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='active',
        ),
        migrations.AddField(
            model_name='token',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
