# Generated by Django 5.2.5 on 2025-09-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_adminsettings_added_slipage_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='quotes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
