# Generated by Django 5.2.5 on 2025-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_adminsettings_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='max_sane_gas_price',
            field=models.FloatField(default=4.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('stop_loss_price_increased', 'stop_loss_price_increased'), ('stop_loss_price_occured_but_auto_exit_is_off', 'stop_loss_price_occured_but_auto_exit_is_off'), ('exited', 'exited'), ('transaction_failed', 'transaction_failed')], default='stop_loss_price_increased'),
        ),
    ]
