# Generated by Django 5.2.5 on 2025-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_adminsettings_max_sane_gas_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_min_profit', 'auto_exit_style_only_after_min_profit'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_never'),
        ),
    ]
