# Generated by Django 5.2.7 on 2025-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_token_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='contract',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
