# Generated by Django 5.2.5 on 2025-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_transaction_auto_exit_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='auto_exit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='auto_exit_style',
        ),
        migrations.AddField(
            model_name='position',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_min_profit', 'auto_exit_style_only_after_min_profit'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_never'),
        ),
    ]
