# Generated by Django 5.2.7 on 2025-10-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_token_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='locked_liquidity',
            field=models.BooleanField(default=False),
        ),
    ]
