# Generated by Django 5.2.7 on 2025-10-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_token_locked_liquidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='contract',
            field=models.TextField(blank=True, default='', null=True, unique=True),
        ),
    ]
