# Generated by Django 5.2.5 on 2025-09-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_position_auto_exit_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_min_profit', 'auto_exit_style_only_after_min_profit'), ('auto_exit_style_only_below_stop_loss', 'auto_exit_style_only_below_stop_loss'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_only_after_min_profit'),
        ),
    ]
