# Generated by Django 5.2.7 on 2025-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_token_address_alter_token_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
