# Generated by Django 5.2.7 on 2025-10-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_token_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
