# Generated by Django 5.2.5 on 2025-09-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_position_auto_exit_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='added_slipage_multiplier',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='quotes',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='added_slipage_multiplier_coin_to_fiat',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='added_slipage_multiplier_fiat_to_coin',
            field=models.FloatField(default=3),
        ),
    ]
