# Generated by Django 5.2.5 on 2025-09-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_adminsettings_added_slipage_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('coin', models.CharField(choices=[('weth', 'weth'), ('wsol', 'wsol'), ('wbtc', 'wbtc')], default='weth')),
                ('coin_amount', models.FloatField(default=0)),
                ('entry_capital', models.FloatField(default=0)),
                ('order_price', models.FloatField(default=0)),
                ('min_profit_exit_price', models.FloatField(default=0)),
                ('stop_loss_price', models.FloatField(default=0)),
                ('uuid', models.TextField(blank=True, default='', null=True)),
                ('active', models.BooleanField(default=True)),
                ('attended', models.BooleanField(default=True)),
                ('epoch_created', models.BigIntegerField(default=0)),
                ('epoch_updated', models.BigIntegerField(default=0)),
                ('epoch_attended', models.BigIntegerField(default=0)),
                ('auto_exit_style', models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_min_profit', 'auto_exit_style_only_after_min_profit'), ('auto_exit_style_only_below_stop_loss', 'auto_exit_style_only_below_stop_loss'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_only_after_min_profit')),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='position',
            name='coin_amount',
        ),
        migrations.RemoveField(
            model_name='position',
            name='entry_capital',
        ),
        migrations.RemoveField(
            model_name='position',
            name='name',
        ),
        migrations.RemoveField(
            model_name='position',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='position',
            name='transaction_hash',
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order'),
        ),
    ]
