# Generated by Django 5.2.7 on 2025-10-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_adminsettings_active_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='active_account',
            field=models.CharField(choices=[('account_hedge', 'account_hedge'), ('account_dex', 'account_dex'), ('account_ajax', 'account_ajax'), ('account_eagle', 'account_eagle'), ('account_ranger', 'account_ranger'), ('account_lion', 'account_lion'), ('account_tiger', 'account_tiger')], default='account_hedge'),
        ),
    ]
