# Generated by Django 5.2.5 on 2025-09-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_order_remove_position_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coin_amount',
        ),
        migrations.AddField(
            model_name='position',
            name='coin_amount',
            field=models.FloatField(default=0),
        ),
    ]
