# Generated by Django 5.2.7 on 2025-10-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_adminsettings_active_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='go_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='has_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='has_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='has_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='honeypot_is',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='quick_intel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='token_sniffer',
            field=models.BooleanField(default=False),
        ),
    ]
