# Generated by Django 5.2.5 on 2025-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_order_coin_amount_position_coin_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='attended',
        ),
        migrations.RemoveField(
            model_name='order',
            name='epoch_attended',
        ),
        migrations.AddField(
            model_name='order',
            name='epoch_executed',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='fullfiled',
            field=models.BooleanField(default=False),
        ),
    ]
