# Generated by Django 5.2.7 on 2025-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_token_go_security_token_has_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='orders_paid_for_of_token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='pairs',
        ),
        migrations.RemoveField(
            model_name='token',
            name='pairs_with_the_pair',
        ),
        migrations.RemoveField(
            model_name='token',
            name='pools',
        ),
        migrations.AddField(
            model_name='token',
            name='auto_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
