# Generated by Django 5.2.5 on 2025-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_order_attended_remove_order_epoch_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('buy_if_price_is_above', 'buy_if_price_is_below')], default='buy_if_price_is_above'),
        ),
    ]
