# Generated by Django 5.2.7 on 2025-10-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_token_orders_paid_for_of_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='token',
            name='h24',
        ),
        migrations.RemoveField(
            model_name='token',
            name='h6',
        ),
        migrations.RemoveField(
            model_name='token',
            name='m5',
        ),
    ]
