# Generated by Django 5.2.5 on 2025-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_order_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('buy_if_price_is_above', 'buy_if_price_is_above'), ('buy_if_price_is_below', 'buy_if_price_is_below')], default='buy_if_price_is_below'),
        ),
    ]
