# Generated by Django 5.2.7 on 2025-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_token_h1_remove_token_h24_remove_token_h6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='age',
        ),
        migrations.AddField(
            model_name='token',
            name='epoch_created',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
