# Generated by Django 5.2.5 on 2025-09-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_order_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='thread_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
