# Generated by Django 5.2.5 on 2025-09-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_adminsettings_thread_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='running',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='thread_name',
        ),
    ]
