# Generated by Django 5.2.7 on 2025-10-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_token_age_token_epoch_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
