# Generated by Django 5.2.7 on 2025-10-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_token_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='image',
        ),
        migrations.AddField(
            model_name='token',
            name='image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
