# Generated by Django 5.2.5 on 2025-09-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_adminsettings_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='pulse_locked',
            field=models.BooleanField(default=False),
        ),
    ]
