# Generated by Django 5.2.7 on 2025-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_token_image_token_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='show_on_chart',
            field=models.BooleanField(default=True),
        ),
    ]
