# Generated by Django 5.2.5 on 2025-09-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_adminsettings_pulse_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='pulse_locked',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='pulses_are_being_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('token_to_fiat', 'token_to_fiat'), ('fiat_to_token', 'fiat_to_token'), ('wrap_eth', 'wrap_eth'), ('unwrap_weth', 'unwrap_weth')], default='token_to_fiat'),
        ),
    ]
