# Generated by Django 5.2.7 on 2025-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_token_show_on_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='already_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
