# Generated by Django 5.2.5 on 2025-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_adminsettings_pulse_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='depth_cluster_width_usd',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='depth_filtering_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='depth_highest_price',
            field=models.FloatField(default=5000),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='depth_lowest_price',
            field=models.FloatField(default=4000),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='depth_show_cumulative',
            field=models.BooleanField(default=False),
        ),
    ]
