# Generated by Django 5.2.5 on 2025-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_adminsettings_depth_cluster_width_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='depth_filtering_active',
            field=models.BooleanField(default=True),
        ),
    ]
