# Generated by Django 5.2.7 on 2025-10-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_token_already_alerted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='go_security',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='has_telegram',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='has_twitter',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='has_website',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='honeypot_is',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='locked_liquidity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='quick_intel',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_sniffer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
