# Generated by Django 5.2.5 on 2025-09-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alter_adminsettings_depth_filtering_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='depth_cluster_width_usd',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='depth_highest_price',
            field=models.FloatField(default=4400),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='depth_lowest_price',
            field=models.FloatField(default=4200),
        ),
    ]
