# Generated by Django 5.2.5 on 2025-09-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_alter_adminsettings_depth_cluster_width_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='depth_cluster_width_usd',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='fiat_coin',
            field=models.CharField(choices=[('usdc', 'usdc')], default='usdc'),
        ),
        migrations.AlterField(
            model_name='candle',
            name='coin',
            field=models.CharField(choices=[('weth', 'weth')], default='weth'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coin',
            field=models.CharField(choices=[('weth', 'weth')], default='weth'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.CharField(choices=[('weth', 'weth')], default='weth'),
        ),
    ]
