# Generated by Django 5.2.5 on 2025-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_adminsettings_depth_cluster_width_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
