# Generated by Django 5.2.5 on 2025-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_order_archived_position_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='exited_gracefully',
            field=models.BooleanField(default=False),
        ),
    ]
