# Generated by Django 5.2.5 on 2025-09-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_position_exited_gracefully'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='tx_tries',
            field=models.IntegerField(default=2),
        ),
    ]
