# Generated by Django 5.2.5 on 2025-09-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_adminsettings_tx_tries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('epoch', models.BigIntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
