# Generated by Django 5.2.5 on 2025-09-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_tick'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candle',
        ),
    ]
