# Generated by Django 5.2.5 on 2025-09-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_delete_candle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField(blank=True, default='', null=True)),
                ('alert_type', models.CharField(choices=[('price_goes_above', 'price_goes_above'), ('price_goes_below', 'price_goes_below')], default='price_goes_above')),
                ('alert_price', models.FileField(default=0, upload_to='')),
                ('epoch_created', models.BigIntegerField(default=0)),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
