# Generated by Django 5.2.5 on 2025-09-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_price',
            field=models.FloatField(default=0),
        ),
    ]
