# Generated by Django 5.2.5 on 2025-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_alter_alert_alert_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='added_slipage_multiplier_coin_to_fiat',
        ),
        migrations.RemoveField(
            model_name='adminsettings',
            name='added_slipage_multiplier_fiat_to_coin',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='slipage',
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='added_slippage_multiplier_coin_to_fiat',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='added_slippage_multiplier_fiat_to_coin',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='slippage',
            field=models.FloatField(default=0),
        ),
    ]
