# Generated by Django 5.2.5 on 2025-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_remove_adminsettings_added_slipage_multiplier_coin_to_fiat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='min_profit_exit_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='growth_percentage_from_min_profit_exit_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='min_profit_exit_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='profit_amount_at_min_profit_exit_price',
        ),
        migrations.AddField(
            model_name='order',
            name='profit_take_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='growth_percentage_from_profit_take_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='profit_amount_at_profit_take_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='profit_take_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='state',
            field=models.CharField(choices=[('in_loss', 'in_loss'), ('reaching_profit_take_price', 'reaching_profit_take_price'), ('post_profit_take_price', 'post_profit_take_price'), ('exited_in_loss', 'exited_in_loss'), ('exited_in_profit', 'exited_in_profit')], default='reaching_profit_take_price'),
        ),
    ]
