# Generated by Django 5.2.5 on 2025-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_remove_order_min_profit_exit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_profit_take_price_reached', 'auto_exit_style_only_after_profit_take_price_reached'), ('auto_exit_style_only_below_stop_loss', 'auto_exit_style_only_below_stop_loss'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_only_after_profit_take_price_reached'),
        ),
        migrations.AlterField(
            model_name='position',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_profit_take_price_reached', 'auto_exit_style_only_after_profit_take_price_reached'), ('auto_exit_style_only_below_stop_loss', 'auto_exit_style_only_below_stop_loss'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_only_after_profit_take_price_reached'),
        ),
    ]
