# Generated by Django 5.2.5 on 2025-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_order_auto_exit_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fullfiled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mode',
        ),
        migrations.AddField(
            model_name='order',
            name='entry_condition',
            field=models.CharField(choices=[('buy_if_price_is_above', 'buy_if_price_is_above'), ('buy_if_price_is_below', 'buy_if_price_is_below'), ('sell_if_price_is_above', 'sell_if_price_is_above'), ('sell_if_price_is_below', 'sell_if_price_is_below')], default='buy_if_price_is_below'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='position_type',
            field=models.CharField(choices=[('short', 'short'), ('long', 'long')], default='long'),
        ),
        migrations.AlterField(
            model_name='order',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_profit_take_price_reached', 'auto_exit_style_only_after_profit_take_price_reached'), ('auto_exit_style_only_after_stop_loss_price_reached', 'auto_exit_style_only_after_stop_loss_price_reached'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_only_after_profit_take_price_reached'),
        ),
        migrations.AlterField(
            model_name='position',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_profit_take_price_reached', 'auto_exit_style_only_after_profit_take_price_reached'), ('auto_exit_style_only_after_stop_loss_price_reached', 'auto_exit_style_only_after_stop_loss_price_reached'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_only_after_profit_take_price_reached'),
        ),
    ]
