# Generated by Django 5.2.5 on 2025-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_order_fullfiled_remove_order_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fiat_amount_recieved',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='token_amount_recieved',
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiat_amount_received',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token_amount_received',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_condition',
            field=models.CharField(choices=[('execute_if_price_is_above', 'execute_if_price_is_above'), ('execute_if_price_is_below', 'execute_if_price_is_below')], default='execute_if_price_is_below'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('transaction_state_ongoing', 'transaction_state_ongoing'), ('transaction_state_failed', 'transaction_state_failed'), ('transaction_state_successful', 'transaction_state_successful')], default='transaction_state_ongoing'),
        ),
    ]
