# Generated by Django 5.2.5 on 2025-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_transaction_fiat_amount_recieved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('token_to_fiat', 'token_to_fiat'), ('fiat_to_token', 'fiat_to_token'), ('wrap_eth', 'wrap_eth'), ('unwrap_weth', 'unwrap_weth'), ('supply', 'supply'), ('withdraw', 'withdraw'), ('borrow', 'borrow'), ('repay', 'repay')], default='token_to_fiat'),
        ),
    ]
