# Generated by Django 5.2.5 on 2025-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='gas_speed',
            field=models.CharField(choices=[('FastGasPrice', 'FastGasPrice'), ('SafeGasPrice', 'SafeGasPrice'), ('ProposeGasPrice', 'ProposeGasPrice')], default='FastGasPrice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('uniswap_approve', 'uniswap_approve'), ('uniswap_token_to_fiat', 'uniswap_token_to_fiat'), ('uniswap_fiat_to_token', 'uniswap_fiat_to_token'), ('uniswap_wrap_eth', 'uniswap_wrap_eth'), ('uniswap_unwrap_weth', 'uniswap_unwrap_weth'), ('aave_approve', 'aave_approve'), ('aave_supply', 'aave_supply'), ('aave_withdraw', 'aave_withdraw'), ('aave_borrow', 'aave_borrow'), ('aave_repay', 'aave_repay')], default='uniswap_token_to_fiat'),
        ),
    ]
