# Generated by Django 5.2.5 on 2025-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_adminsettings_gas_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='pulse_counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='gas_speed',
            field=models.CharField(choices=[('FastGasPrice', 'FastGasPrice'), ('ProposeGasPrice', 'ProposeGasPrice'), ('SafeGasPrice', 'SafeGasPrice')], default='FastGasPrice'),
        ),
    ]
