# Generated by Django 5.2.5 on 2025-09-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_adminsettings_pulse_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='aave_info_update_pulse_steps',
            field=models.IntegerField(default=10),
        ),
    ]
