# Generated by Django 5.2.5 on 2025-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_adminsettings_aave_info_update_pulse_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='aave_user_account_data',
            field=models.JSONField(default=dict),
        ),
    ]
