# Generated by Django 5.2.5 on 2025-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_adminsettings_aave_user_account_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='gas_update_epoch_max_allowed_delay_seconds',
            field=models.IntegerField(default=10),
        ),
    ]
