# Generated by Django 5.2.5 on 2025-09-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_adminsettings_gas_update_epoch_max_allowed_delay_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_entry_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='entry_condition',
            field=models.CharField(choices=[('execute_if_price_is_above', 'execute_if_price_is_above'), ('execute_if_price_is_below', 'execute_if_price_is_below')], default='auto_exit_style_both_ways'),
        ),
    ]
