# Generated by Django 5.2.5 on 2025-09-19 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_remove_order_order_price_order_order_entry_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='growth_percentage_from_profit_take_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='growth_percentage_from_stop_loss_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='stop_loss_price_increased',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='stop_loss_price_improved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.order'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('stop_loss_price_improved', 'stop_loss_price_improved'), ('stop_loss_price_occured_but_auto_exit_is_off', 'stop_loss_price_occured_but_auto_exit_is_off'), ('exited', 'exited'), ('transaction_failed', 'transaction_failed')], default='stop_loss_price_improved'),
        ),
        migrations.AlterField(
            model_name='position',
            name='auto_exit_style',
            field=models.CharField(choices=[('auto_exit_style_both_ways', 'auto_exit_style_both_ways'), ('auto_exit_style_only_after_profit_take_price_reached', 'auto_exit_style_only_after_profit_take_price_reached'), ('auto_exit_style_only_after_stop_loss_price_reached', 'auto_exit_style_only_after_stop_loss_price_reached'), ('auto_exit_style_never', 'auto_exit_style_never')], default='auto_exit_style_both_ways'),
        ),
        migrations.AlterField(
            model_name='position',
            name='display_on_chart',
            field=models.BooleanField(default=False),
        ),
    ]
