# Generated by Django 5.2.5 on 2025-09-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_remove_position_growth_percentage_from_profit_take_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_long',
            field=models.BooleanField(default=False),
        ),
    ]
