# Generated by Django 5.2.5 on 2025-09-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_position_is_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='coin_amount',
        ),
        migrations.AddField(
            model_name='position',
            name='coin_amount_borrowed_to_enter_short',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='coin_amount_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='fiat_amount_received_to_sell_and_enter_short',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='fiat_amount_spent_to_buy_and_exit_short',
            field=models.FloatField(default=0),
        ),
    ]
