# Generated by Django 5.2.5 on 2025-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_remove_position_coin_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='aave_borrow_to_collateral_added_safety_ratio',
            field=models.FloatField(default=0.9),
        ),
    ]
