# Generated by Django 5.2.5 on 2025-09-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_adminsettings_aave_borrow_to_collateral_added_safety_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='aave_borrow_to_collateral_added_safety_ratio',
            field=models.FloatField(default=0.9, help_text="a safety margin to make sure we won't borrow all of the borrow amount"),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='aave_info_update_pulse_steps',
            field=models.IntegerField(default=10, help_text='this is how many pulses to skip until the next update of aave user account data'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='aave_user_account_data',
            field=models.JSONField(default=dict, help_text='results from aave contract method for user data is stored here'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='interval',
            field=models.IntegerField(default=5, help_text='pulses interval in seconds'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='max_sane_gas_price',
            field=models.FloatField(default=4.0, help_text='maximum gas price under which all tx are allowed to execute'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='pulse_counter',
            field=models.BigIntegerField(default=0, help_text='this is used to keep track of updating the aave user data'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='secure_profit_ratio',
            field=models.FloatField(default=0.7, help_text='this is used to improve stop loss in case a profit take price is reached'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='tx_tries',
            field=models.IntegerField(default=2, help_text='how many times a uniswap swap will repeat at max (in case of a failure)'),
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.TextField(blank=True, default='', null=True)),
                ('epoch_created', models.BigIntegerField(default=0)),
                ('long_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_position', to='dashboard.position')),
                ('short_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_position', to='dashboard.position')),
            ],
        ),
    ]
