# Generated by Django 5.2.5 on 2025-09-19 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_adminsettings_aave_borrow_to_collateral_added_safety_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='long_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_order', to='dashboard.order'),
        ),
        migrations.AddField(
            model_name='pair',
            name='short_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_order', to='dashboard.order'),
        ),
    ]
