# Generated by Django 5.2.5 on 2025-09-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_pair_long_order_pair_short_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='long_order',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='short_order',
        ),
        migrations.AddField(
            model_name='order',
            name='pair_uuid',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
