# Generated by Django 5.2.5 on 2025-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_remove_pair_long_order_remove_pair_short_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='borrow_from_aave',
            field=models.BooleanField(default=False),
        ),
    ]
