# Generated by Django 5.2.5 on 2025-09-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_adminsettings_borrow_from_aave'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fiat_loan_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('uniswap_approve', 'uniswap_approve'), ('uniswap_token_to_fiat', 'uniswap_token_to_fiat'), ('uniswap_fiat_to_token', 'uniswap_fiat_to_token'), ('uniswap_wrap_eth', 'uniswap_wrap_eth'), ('uniswap_unwrap_weth', 'uniswap_unwrap_weth'), ('aave_approve', 'aave_approve'), ('aave_supply', 'aave_supply'), ('aave_withdraw', 'aave_withdraw'), ('aave_borrow', 'aave_borrow'), ('aave_repay', 'aave_repay'), ('arbi_balance', 'arbi_balance'), ('arbi_action_2', 'arbi_action_2'), ('arbi_approve', 'arbi_approve'), ('arbi_allowance', 'arbi_allowance'), ('arbi_deposit', 'arbi_deposit'), ('arbi_withdraw', 'arbi_withdraw')], default='uniswap_token_to_fiat'),
        ),
    ]
