# Generated by Django 5.2.5 on 2025-09-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interval', models.CharField(choices=[('1s', '1s'), ('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('30m', '30m'), ('1h', '1h')], default='1s')),
                ('open_time', models.BigIntegerField(default=0, unique=True)),
                ('open', models.FloatField(default=0)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('close_time', models.BigIntegerField(default=0)),
            ],
        ),
    ]
