# Generated by Django 5.2.5 on 2025-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_candle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('epoch', models.BigIntegerField(default=0, unique=True)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Candle',
        ),
    ]
