# Generated by Django 5.2.5 on 2025-09-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_price_delete_candle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='data',
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_hourly',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_minutely',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tick',
            name='epoch',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
