# Generated by Django 5.2.5 on 2025-09-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_delete_price_remove_tick_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='indicator_ema_hourly',
        ),
        migrations.RemoveField(
            model_name='tick',
            name='indicator_ema_minutely',
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_hourly_20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_hourly_200',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_hourly_50',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_minutely_20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_minutely_200',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tick',
            name='indicator_ema_minutely_50',
            field=models.FloatField(default=0),
        ),
    ]
