# Generated by Django 5.2.5 on 2025-10-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_remove_tick_indicator_ema_hourly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='uniswap_version',
        ),
    ]
